Sunwell node
HearthSim/Sunwell pull request #24
Opened 2016-12-06 04:06 UTC by martinbonnin

type `node generate_images.js enUS frFR koKR ...` to generate all the PNGs

requires a bunch of dependencies, artwork and font files. One kye dependency is very updated node-canvas to have support for font loading.

2016-12-06 13:20 UTC, jleclanche requested changes
Looks great. Couple changes to squash and this can be merged.

2016-12-06 13:20 UTC, jleclanche commented on generate_images.js
> +console.log("hello");
hello!

2016-12-06 13:20 UTC, jleclanche commented on generate_images.js
> +console.log("hello");
This whole file contains a lot of unnecessary logging/debug stuff. Did you mean to commit it?

2016-12-06 13:20 UTC, jleclanche commented on generate_images.js
> +		downloadJson("https://api.hearthstonejson.com/v1/15590/" + lang + "/cards.json");
Can you make this a global/configurable somehow? You can also use `latest` instead of  a build to always get the latest one.

2016-12-06 16:49 UTC, andburn commented
You could maybe add a small piece in the Readme about it, dependencies and such. This is what I needed anyway:
```
sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
npm install -g node-gyp
npm install github:automattic/node-canvas
npm install mkdirp
npm install promise
npm install request
```

2016-12-06 17:54 UTC, martinbonnin commented on generate_images.js
> +console.log("hello");
I just removed some of it. I still it find interesting to have the current progress of the operation though so I kept the 'save x/2819 XX.png'

2016-12-06 18:10 UTC, martinbonnin commented on generate_images.js
> +		downloadJson("https://api.hearthstonejson.com/v1/15590/" + lang + "/cards.json");
done

2016-12-06 18:17 UTC, martinbonnin commented
Good idea for the readme, I just added a papragraph. Else, I use this bootstrap script to setup my dev environment: https://gist.github.com/martinbonnin/af2df4d1f1eadaa05645a22512556413. Maybe we could version control that somewhere

2016-12-07 07:47 UTC, jleclanche commented
Landed in a328138acfc0ec5bbb2e165f319cf0107b5a6685

2016-12-07 07:47 UTC, closed without merging